version: "3"
services:
  temporal_tctl:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3778:3778"
    environment:
      - NODE_ENV=developed
    volumes:
      - .:/app
