version: "3"
services:
  temporal_tctl:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3778:3778"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    networks:
      - $TEMPORAL_EXTERNAL_NETWORK
networks:
  temporal-network:
    name: $TEMPORAL_EXTERNAL_NETWORK
    external: true